### ISSUE TITLE
Bug: Unable to use ledger on MacOS Sonoma 

### ISSUE THREAD

**Issue by jhernandezb** [cosmos/ledger-cosmos#101]
Seems like enumerating comes with an empty device path causing the OpenDevice to fail.

I've tested this fix https://github.com/Zondax/hid/pull/15 and seems like it works

**Comment by ftheirs** [comment]
Hi @jhernandezb , thanks for the report! There is a new ledger-cosmos-go version! Can you double check to confirm if everything works with the latest release? 🙏 
https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.13.2

**Comment by jhernandezb** [comment]
It works thank you ! although there is no v0.12.x I bumped the `hid` dependency directly to test it.

**Comment by ftheirs** [comment]
awesome! I'll add the fix to **v0.12.x** too 😃

**Comment by ftheirs** [comment]
[v0.12.4](https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.12.4) published! Thanks for the help @jhernandezb 🤗
