### ISSUE TITLE
Max number of tokens limits usability for Nano S

### ISSUE THREAD

**Issue by jhernandezb** [cosmos/ledger-cosmos#109]
Recent version of the app reduced the number of tokens in JSON parser from 96 to 70 impacting usability for Nano S users on Cosmos chains that use CosmWasm where the JSON payload are a bit bigger. 

We have had users that they cannot longer perform actions that were fine before the upgrade but now they get `JSON too big errors`.

https://twitter.com/jhernandezb_/status/1745485753474281645

**Comment by ftheirs** [comment]
Hey @jhernandezb, thanks for reporting this issue! We'll work to solve this asap 🙏

**Comment by jhernandezb** [comment]
Any updates on this? This is currently affecting a good number of users

**Comment by startyNFT** [comment]
Would really appreciate an update, several users are unable to perform actions on Stargaze because of this issue @ftheirs

**Comment by vforgeoux-ledger** [comment]
Hey @jhernandezb @startyNFT , would you be able to provide concrete dApps interactions that are failing with the current Cosmos app version on Nano S ? This way I'll be able to give it a try with the fix we're testing. Thanks!

**Comment by ainhoa-a** [comment]
Fix was already submitted and testing by Ledger is in progress https://github.com/LedgerHQ/app-cosmos/pull/34

**Comment by jhernandezb** [comment]
> Hey @jhernandezb @startyNFT , would you be able to provide concrete dApps interactions that are failing with the current Cosmos app version on Nano S ? This way I'll be able to give it a try with the fix we're testing. Thanks!

we do have a few examples 
```
{
  "account_number": "202429",
  "chain_id": "stargaze-1",
  "fee": {
    "gas": "369729",
    "amount": [
      {
        "amount": "0",
        "denom": "ustars"
      }
    ]
  },
  "memo": "",
  "msgs": [
    {
      "type": "wasm/MsgExecuteContract",
      "value": {
        "contract": "stars1d5frtu2txpy2c5v9jg60wqju2qk8cm8xg3k7s4k863m4hg9mt70sxlxtq2",
        "funds": [],
        "msg": {
          "approve": {
            "expires": {
              "at_time": "1711552995271000000"
            },
            "spender": "stars1fvhcnyddukcqfnt7nlwv3thm5we22lyxyxylr9h77cvgkcn43xfsvgv0pl",
            "token_id": "109"
          }
        },
        "sender": "stars1v7fx7cuum5xz4yu39dwxs7mlje3yptl3k7wum2"
      }
    },
    {
      "type": "wasm/MsgExecuteContract",
      "value": {
        "contract": "stars1fvhcnyddukcqfnt7nlwv3thm5we22lyxyxylr9h77cvgkcn43xfsvgv0pl",
        "funds": [
          {
            "amount": "500000",
            "denom": "ustars"
          }
        ],
        "msg": {
          "set_ask": {
            "collection": "stars1d5frtu2txpy2c5v9jg60wqju2qk8cm8xg3k7s4k863m4hg9mt70sxlxtq2",
            "expires": "1711552995271000000",
            "funds_recipient": "stars1v7fx7cuum5xz4yu39dwxs7mlje3yptl3k7wum2",
            "price": {
              "amount": "10000000000",
              "denom": "ustars"
            },
            "reserve_for": null,
            "sale_type": "fixed_price",
            "token_id": 109
          }
        },
        "sender": "stars1v7fx7cuum5xz4yu39dwxs7mlje3yptl3k7wum2"
      }
    }
  ],
  "sequence": "8"
}
```

We also have our testnet you can play with if you need so.

**Comment by vforgeoux-ledger** [comment]
The Cosmos app has been updated to `2.34.14` version. You can install it from Ledger Live My Ledger tab.

(cc @jhernandezb @startyNFT )

**Comment by jhernandezb** [comment]
Thanks! Working now
