### ISSUE TITLE
Can't send funds from INJ account

### ISSUE THREAD

**Issue by liviumanea** [cosmos/ledger-cosmos#110]
I tried sending some funds from my INJ account using ledger live. On the first attempt it wanted to activate Advanced mode which I did. The first transaction went through succesfully. I then tried making another transaction and I keep getting the error:

invalid broadcast return (code: 32, message: 'account sequence mismatch, expected 1, got 0: incorrect account sequence')

Indeed, on my Ledger device I see the sequence 0 listed.

the version of my Cosmos app is v2.34.12

Can you please help ?

**Comment by ftheirs** [comment]
Hi @liviumanea, I haven't seen this error but I can tell you that if you're able to review and sign the transaction, the issue is on the wallet. Can you check using Keplr or Cosmostation?

**Comment by ftheirs** [comment]
I'll close the issue due to a lack of response. Feel free to reopen it 😄
