### ISSUE TITLE
Add support for arbitrary messages

### ISSUE THREAD

**Issue by jleni** [cosmos/ledger-cosmos#18]
SDK discussion: https://github.com/cosmos/cosmos-sdk/issues/4581

**Comment by yun-yeo** [comment]
Hey @jleni, many terra community members want this feature from contract side to verify something. 
Is there any progress on this issue?

**Comment by blake-regalia** [comment]
There is a specification for this now: https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-036-arbitrary-signature.md

**Comment by jleni** [comment]
This will be handled as part of sign mode textual. 
We are waiting for the team to provide specifications to start development
