### ISSUE TITLE
add key, ERROR: address  rejected

### ISSUE THREAD

**Issue by Xa52c** [cosmos/ledger-cosmos#28]
gaiacli keys add test_ledger --ledger
ERROR: address  rejected

ledger v1.6.0
cosmos app: v2.12.0

client_name: gaiacli
version: 2.0.10

**Comment by shieldstar** [comment]
Same issue with ledger 1.6.0 / cosmos app v2.14.0 / gaiacli 2.0.10

**Comment by jleni** [comment]
This is known issue in gaiacli:  https://github.com/cosmos/cosmos-sdk/issues/6313
