### ISSUE TITLE
Missing root pages when signing tx

### ISSUE THREAD

**Issue by rhuairahrighairidh** [cosmos/ledger-cosmos#29]
After adding an address via cli, only the first two pages (Chain ID and Account) are shown when signing a tx.

No other pages can be accessed (though a double click jumps to the end menu where the tx can be succesfully signed)
Powering the ledger off and on fixes this issue and all pages for the tx are shown.

Steps to Reproduce:
- install [kava](https://github.com/kava-labs/kava) v0.8.1 (`git clone ...`, `make install`)
- add a new key to the cli store: `kvcli keys add ledgertest --ledger --legacy-hd-path`
- create a json tx to sign: `kvcli tx send (kvcli keys show ledgertest -a) kava1adkm6svtzjsxxvg7g6rshg6kj9qwej8gwqadqd 1ukava --from ledgertest --generate-only > tx.json`
- initiate signing: `kvcli tx sign tx.json --from ledgertest --account-number 0 --sequence 0 --offline`

The first two pages Chain ID and Account will be accessible but not any others. If you unplug the ledger and plug it back in and run the last step it will work as expected - all pages will be visible.

Note:
- kava uses cosmos-sdk v0.38.4.
- I've verified that the bytes sent to the ledger are identical between the tx that showed all pages and the tx that didn't

**Comment by jleni** [comment]
This should have been fixed in v2.15.0 (This version is planned for release by Ledger)
Please reopen if that is not the case.

**Comment by rhuairahrighairidh** [comment]
Thanks! verified as working in v2.16.1
