### ISSUE TITLE
Cosmos app v2.16.1 not working with command line

### ISSUE THREAD

**Issue by godas14** [cosmos/ledger-cosmos#32]
After upgrade app Cosmos to new v2.16.1 the app do not "Show Address" in menu
as before in v1.5.3
I use commands line in Terminal of my Mac. I open Cosmos app
When I try to make transaction the following error shown:
Please see below error
confirm transaction before signing and broadcasting [y/N]: y
ERROR: please open Cosmos app on the Ledger device - error: [APDU_CODE_INS_NOT_SUPPORTED] Instruction code not supported or invalid

**Comment by jleni** [comment]
Hi @godas14 , 
I actually meant to open here only the issue about:

> After upgrade app Cosmos to new v2.16.1 the app do not "Show Address" in menu
as before in v1.5.3

the other one is actually related to gaia, not the ledger app
