### ISSUE TITLE
use hw-transport-u2f

### ISSUE THREAD

**Issue by yuzhiyou1990** [cosmos/ledger-cosmos#33]
Error:
{return_code: 25600, error_message: "App Version is not supported"}

Browser:
Chrome

Ledger Cosmos App:
v2.16.1

Code:
```javascript
import TransportU2F from "@ledgerhq/hw-transport-u2f";

const transport = await TransportU2F.create();
const app = new CosmosApp(transport);
const response = await app.getAddressAndPubKey([44, 118, 5, 0, 3], "cosmos");
```

other:
https://github.com/LedgerHQ/ledgerjs/issues/413

I'm trying to integrating a ledger nano s inside a chrome extension.

**Comment by jleni** [comment]
U2F was been deprecated by Ledger for a long time already.
