### ISSUE TITLE
Support gRPC transactions

### ISSUE THREAD

**Issue by buuni** [cosmos/ledger-cosmos#39]
Not so long ago, Cosmos migrated from Rest API to gRPC, in this regard, the format of transactions for sending through the `cosmos.tx.v1beta1.Service/BroadcastTx` service has changed.
This kind of transaction cannot currently be signed via the ledger-app.
Do you plan to support gRPC transactions in ledger-app?

Thank you in advance.

**Comment by jleni** [comment]
Could you provide more information / context ?

REST/gRPC are protocols that are related to completely other layers.

Ledger apps receive a small tx blob and work along USB/Bluetooth. There is no network endpoint in this layer.

**Comment by faboweb** [comment]
@buuni Are you working with https://github.com/cosmos/cosmjs to facilitate signing?

**Comment by jleni** [comment]
Closing as this it not part of the scope of a Ledger app
