### ISSUE TITLE
Cant add  Atom account to ledger live desktop

### ISSUE THREAD

**Issue by domashno** [cosmos/ledger-cosmos#40]
![image](https://user-images.githubusercontent.com/32385410/133858199-55506188-5aba-49cf-9ff4-d3d8ca8db3ed.png)

Hope helps

**Comment by jleni** [comment]
This seems to be related to a problem in Ledger Live when parsing the server response:

> can't parse server result SyntaxError: Unexpected token h in JSON at position 1

This seemed to happened when retrieving chain data

![image](https://user-images.githubusercontent.com/13698520/133976250-00f1a6c4-8e74-40b8-9f37-9814c3c3b6c0.png)

This is not a problem on the app itself but in the Live desktop app. Nevertheless, we will contact Ledger and inform them about this issue.

**Comment by domashno** [comment]
thank you
