### ISSUE TITLE
Ledger + gravitybridge character gives error

### ISSUE THREAD

**Issue by Byte1122** [cosmos/ledger-cosmos#54]
Trying to bridge with IBC from Gravity to Cosmos. Kepler throws an error:

- "Data is invalid: Unexpected characters"

**Comment by puneet2019** [comment]
Hey! have seend this error, use the `window.getOfflineSignerOnlyAmino(chainID)` method or `window.getOfflineSignerAuto(chainID)` , ledger only signs amino messages, so if they are custom messages make sure they have amino support in gravity bridge.

**Comment by ftheirs** [comment]
Hi @Byte1122! Could you provide more info so we can reproduce this?
App version, firmware version and if you have the transaction would be great 😄

**Comment by ainhoa-a** [comment]
Hi, just wanted to inform you that the Cosmos 2.34.6 update has been published and is now available in Ledger Live manager on LNS,LNS+, and LNX :LedgerWallet. This update solves the issue described here.
