### ISSUE TITLE
Ledger live problem

### ISSUE THREAD

**Issue by ghost** [cosmos/ledger-cosmos#61]
After creating an address on cosmos Ledger Live, the message "Verify that your physical wallet is configured with the recovery phrase associated with the selected account." appears systematically whereas I use the right key and I have no problem on the other cryptos.
When I create a new account on Ledger Live I have a different cosmos address yet I have the same path.
To get my receiving address on my first account, I have to open the cosmos app on my Ledger, and wait for the device to screenlock, then I have my first address.
If I don't wait for the device to screenlock and I'm in the cosmos app, I'll get the second address.
I think when the app is in sleep mode, we are pointing to a different path than what is displayed or to a random address.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=i72OLqwyQBk

**Comment by ghost** [comment]
Here is the video where I explain the problem.

I tried with another Ledger and I have the same address that appears.

**Comment by ftheirs** [comment]
Hi @LaugierHugo, thanks for reporting this issue! It's fixed now 🙂

**Comment by ghost** [comment]
Hello, thank you for your feedback.
Very well for the corrected problem, but how do I do on my side to recover on the blocked address?
@ftheirs

**Comment by ghost** [comment]
@ftheirs
