### ISSUE TITLE
Advanced Log in Ledger shows wrong prefix for xpub

### ISSUE THREAD

**Issue by philipglazman** [cosmos/ledger-cosmos#62]
In Ledger Live, the `Advanced Logs` object shows an xpub value with the regular cosmos account human-readable prefix (`cosmos`) instead of the bech32 public key prefix (`cosmospub`). 

If I recall, an earlier version did in fact display the correct prefix so there might be a regression? 

Please let me know if this is the wrong place to file this issue! Thanks!

**Comment by jleni** [comment]
This bug applies to Ledger Live, not the cosmos app.
