### ISSUE TITLE
Ledger: Fail to send token: Data is invalid : Unrecognized error code

### ISSUE THREAD

**Issue by c-michail** [cosmos/ledger-cosmos#65]
After updating the cosmos app on the ledger i can't send through IBC.
I throws: Fail to send token: Data is invalid : Unrecognized error code

To Reproduce

    Update your ledger device with the latest cosmos app
    From keprl go to osmosis chain
    Select an IBC token (eg. Juno) and sent it to another Osmosis address (don't use IBC transfer, click on the asset!)
    You'll get Fail to send token: Data is invalid : Unrecognized error code

Before the update of the cosmos app on ledger it worked.
Anyhow only the IBC transfer doesn't work the the updated cosmos app on ledger.

Expected behavior
To send the token to the other address

So something has changed either from the cosmos ledger app or the keprl.

Thank you

Reported the same issue on Keprl's github they think it's your issue:
https://github.com/chainapsis/keplr-wallet/issues/368

Thanks

**Comment by akrueger** [comment]
I also have this issue with Terra IBC tokens (SCRT, OSMO, ATOM) when sending between two Terra wallets.

Also reported this to Keplr team and they feel it's the Ledger Cosmos app.

**Comment by gickyDEV** [comment]
Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.

**Comment by mrlp4** [comment]
I had the same issue, and after some discovering with osmosis cli i found up that cosmos app on ledger wont accept token denom  longer that 49 symbols. I found that it only related to transfer transaction, swap or IBC send works well.
Got it confirmed with multiple chains - Juno, Osmosis, Bostrom. At every one native tokens (with short denom) sends work, wile non-native dont.  
Everything works well with 2.18.0 cosmos app
Does not work with  2.34.4 app on either x or s ledger on latest firmware.

**Comment by c-michail** [comment]
The problem is that we can not revert back until the fix it!

**Comment by intercos** [comment]
The issue of IBC token send impossible
It's definitely something to do with the Cosmos App update.
https://github.com/chainapsis/keplr-wallet/issues/368#issuecomment-1145385768

**Comment by c-michail** [comment]
Can anybody fix it please ?  Devs seems not looking the "issue" list!

Thank you

**Comment by Terminal-Geek** [comment]
This bug makes it impossible, to supply any IBC assets to Kava lend or to withdraw. So my Atom is stuck there. Please fix.

<img width="357" alt="ledger_ibc_bug" src="https://user-images.githubusercontent.com/8039316/172047849-8412fd5b-311e-47c3-b6b1-8aca0a0d290a.png">

**Comment by wickles** [comment]
Cameron from Kava Labs has been saying that they have posted a PR to fix this over a month ago but it has not been accepted yet. I have not been able to find that PR but he claims the Kava team has been in contact with the Ledger team about it. It seems like there is some seriously poor communication between the teams in resolving this issue. Please get it together. @Kava-Labs @LedgerHQ @Zondax 

<img width="391" alt="Screen Shot 2022-06-05 at 10 11 22 AM" src="https://user-images.githubusercontent.com/4229542/172062097-a3de7cc6-e0ae-4399-8c65-baa476233a16.png">

<img width="396" alt="Screen Shot 2022-06-05 at 10 14 44 AM" src="https://user-images.githubusercontent.com/4229542/172062236-6c8b1d8e-1e76-496e-a571-a0cc1e64aebe.png">

**Comment by c-michail** [comment]
@ftheirs @Saltari  Anyone of you alive or dead ? We need a FUCKING FIX for GOD SAKE! 

Thank you

**Comment by Terminal-Geek** [comment]
PUSH! Any news about this?


> Cameron from Kava Labs has been saying that they have posted a PR to fix this over a month ago but it has not been accepted yet. I have not been able to find that PR but he claims the Kava team has been in contact with the Ledger team about it. It seems like there is some seriously poor communication between the teams in resolving this issue. Please get it together. @Kava-Labs @LedgerHQ @Zondax 
> 
> 
> 
> <img width="391" alt="Screen Shot 2022-06-05 at 10 11 22 AM" src="https://user-images.githubusercontent.com/4229542/172062097-a3de7cc6-e0ae-4399-8c65-baa476233a16.png">
> 
> 
> 
> <img width="396" alt="Screen Shot 2022-06-05 at 10 14 44 AM" src="https://user-images.githubusercontent.com/4229542/172062236-6c8b1d8e-1e76-496e-a571-a0cc1e64aebe.png">
> 
> 
> 
>

**Comment by penguinpablo** [comment]
I have been waiting for a solution for a month now. Can someone pick this up please?
My ATOM tokens are stuck on Kava due to this issue.

**Comment by mrlp4** [comment]
> I have been waiting for a solution for a month now. Can someone pick this up please? My ATOM tokens are stuck on Kava due to this issue.

dude, i'm not a dev here, but can advice you to do IBC transfer instead of normal transfer 
it works for me when i send atoms in osmosis

**Comment by ftheirs** [comment]
Hi everyone! We've made some fixes for IBC and the release is published here: https://github.com/cosmos/ledger-cosmos/releases/tag/v2.34.5

You can install Zondax release only in NanoS and NanoS+:

- Download installer_nanos.sh (or nanos_plus depending on your device)
- Give execution permission (chmod +x installer_nanos.sh)
- Install version 2.34.5 (./installer_nanos.sh load) ---> This will uninstall previous version and then install 2.34.5

We are working to publish a new Ledger official release!

**Comment by c-michail** [comment]
THANKKKKK YOOOUUUUUUUU!!! Finallyyyyyyyyyyyy!!!! 💯 🥳 

Don't forget NanoX!

**Comment by Terminal-Geek** [comment]
> Hi everyone! We've made some fixes for IBC and the release is published here: https://github.com/cosmos/ledger-cosmos/releases/tag/v2.34.5
> 
> 
> 
> You can install Zondax release only in NanoS and NanoS+:
> 
> 
> 
> - Download installer_nanos.sh (or nanos_plus depending on your device)
> 
> - Give execution permission (chmod +x installer_nanos.sh)
> 
> - Install version 2.34.5 (./installer_nanos.sh load) ---> This will uninstall previous version and then install 2.34.5
> 
> 
> 
> We are working to publish a new Ledger official release!

Thank you, looking forward the public release. Do you have an ETA?

Regards

**Comment by ftheirs** [comment]
I will close this issue since it's duplicated. Conversation can be followed here https://github.com/cosmos/ledger-cosmos/issues/66
However, it's a matter of time to get a new cosmos release published by Ledger.
