### ISSUE TITLE
Kava Lend - IBC assets can't be supplied/withdrawn

### ISSUE THREAD

**Issue by Terminal-Geek** [cosmos/ledger-cosmos#66]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.42.0
- Platform and version: MacOS 12.2.1

#### Expected behavior

Supplying IBC assets to Kava lend via kava.io

#### Actual behavior

Supplying/withdrawing IBC assets with the COSMOS app (2.34.4) is no longer possible after one of the latest updates. Assets are stuck. See screenshot with error message below.

#### Steps to reproduce the behavior

Connecting to kava.io. Tried direct connection and Keplr. Kava Telegram community reports same problem with Trust.
Trying to supply to and withdraw from Kava Atom lending pool.

<img width="357" alt="ledger_ibc_bug" src="https://user-images.githubusercontent.com/8039316/172048585-d5e9d3e1-ecfa-46f3-bb9e-55d2ce950f4c.png">

__Originally posted by @Terminal-Geek in https://github.com/LedgerHQ/ledger-live-desktop/issues/4994__

**Comment by kvaintr** [comment]
Confirm. This happens only with IBC assets in one part of the application. This is the message that fails for IBC assets only. If the denom is not ibc (e.g. ukava) then the tx works fine. Keplr without ledger can sign this tx without problems. Keplr+ledger fails. Ledger without Keplr also fails.
```
{
  "chain_id": "kava_2222-10",
  "account_number": "__censored__",
  "sequence": "1",
  "fee": {
    "gas": "1000000",
    "amount": [
      {
        "denom": "ukava",
        "amount": "5000"
      }
    ]
  },
  "msgs": [
    {
      "type": "hard/MsgDeposit",
      "value": {
        "depositor": "__censored__",
        "amount": [
          {
            "denom": "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
            "amount": "299000"
          }
        ]
      }
    }
  ],
  "memo": ""
}
```
A different type of tx with IBC token that works fine and has no issues:
```
{
  "chain_id": "kava_2222-10",
  "account_number": "__censored__",
  "sequence": "1",
  "fee": {
    "gas": "1000000",
    "amount": [
      {
        "denom": "ukava",
        "amount": "5000"
      }
    ]
  },
  "msgs": [
    {
      "type": "swap/MsgSwapExactForTokens",
      "value": {
        "requester": "__censored__",
        "exact_token_a": {
          "denom": "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
          "amount": "1000"
        },
        "token_b": {
          "denom": "usdx",
          "amount": "11225"
        },
        "slippage": "0.001000000000000000",
        "deadline": "1955441587"
      }
    }
  ],
  "memo": ""
}
```
Also IBC transfers are working fine, so the problem is hidden in the first transaction. Probably how it's parsed or presented on Ledger device. Ledger fails with unrecognized error without showing anything on the screen.

**Comment by Terminal-Geek** [comment]
Is this project still alive? @ftheirs @Saltari

**Comment by ftheirs** [comment]
Hi everyone! We've made some fixes for IBC and the release is published here: https://github.com/cosmos/ledger-cosmos/releases/tag/v2.34.5

You can install Zondax release only in NanoS and NanoS+:

- Download installer_nanos.sh (or nanos_plus depending on your device)
- Give execution permission (chmod +x installer_nanos.sh)
- Install version 2.34.5 (./installer_nanos.sh load) ---> This will uninstall previous version and then install 2.34.5

We are working to publish a new Ledger official release!

**Comment by codehans** [comment]
@ftheirs what's the progress with the release of this on Ledger Live please? Ledger don't seem to know anything about it ![image](https://user-images.githubusercontent.com/94654388/177596966-ff6670cb-5fdc-4b13-9261-b3e21851862b.png)

**Comment by ftheirs** [comment]
The PR was created (https://github.com/LedgerHQ/app-cosmos/pull/19) but Ledger needs to perform the security review. However this is only needed for NanoX users. For NanoS and S+, it's possible to user this repo's release in order to move tokens.

**Comment by Terminal-Geek** [comment]
Thanks for the update! Since I'm a NanoX user I'm afraid I have to wait. Any idea how to urge Ledger team to finalize the security check? This bug blocks my tokens for too much time already.

**Comment by ainhoa-a** [comment]
Hi, just wanted to inform you that the Cosmos 2.34.6 update has been published and is now available in Ledger Live manager on LNS,LNS+, and LNX :LedgerWallet. This update solves the issue described here.

**Comment by Rizbe** [comment]
Running `2.34.6` on my ledger nano X and still seeing this issue

**Comment by jleni** [comment]
Could you provide more information about this? We had multiple reports from other people that it was working well. Could you provide more context? What kind of messages are you trying to sign?

**Comment by jleni** [comment]
Just for context, we have a maintenance agreement with Cosmos/ICF, if the problems are very Kava specific, we may need additional information of what kind of messages are being passed. 
Something similar to these test vectors https://github.com/cosmos/ledger-cosmos/issues/66#issuecomment-1146898206 would be very useful

**Comment by Rizbe** [comment]
```
airdrop-a7db1bbd7c5d2915.js:1 claim failed! junoXXXX Error: Data is invalid : Unexpected characters at r (injectedScript.bundle.js:10:32583)
```

**Comment by Rizbe** [comment]
Will post this info soon
https://github.com/cosmos/ledger-cosmos/issues/66#issuecomment-1190025450

**Comment by Rizbe** [comment]
This issue is happening for 
https://gelotto.io/

If you prefer, I can open a new issue instead of using this one

**Comment by ainhoa-a** [comment]
Hi @Rizbe I'm closing this ticket as what your comment about gelotto is a different topic. Please, let's track this separately.
