### ISSUE TITLE
Unable to retrieve my Atom on my Ledger

### ISSUE THREAD

**Issue by ghost** [cosmos/ledger-cosmos#68]
I helped to identify and correct a bug, which consisted in giving a wrong address.

https://github.com/cosmos/ledger-cosmos/issues/61

I was told that the bug had been corrected, but unfortunately no one is helping me get my Atom back.
I helped spontaneously so that this would not happen to other people, I think that my participation allowed the products to be of better quality, I would like now to be helped to recover my Atoms.
My previous ticket was closed by the developer without contacting me.

**Comment by jleni** [comment]
The tickets in this repo track the technical issue on the software published here. 
This is the reason the engineer closed it. 
Having said this, both Ledger and ICF are aware of your situation and I understand it is being discussed at the moment.

**Comment by ghost** [comment]
Thank you very much for your feedback, yes they are aware of my situation.
I'm going to contact them again, hoping to get an answer
