### ISSUE TITLE
UX ideas

### ISSUE THREAD

**Issue by faboweb** [cosmos/ledger-cosmos#7]
- Show the message type first. Most message types are not critical as the user doesn't loose access to  their tokens.
- Show amounts as text: [{amount: 1, denom: uatom}, {amount: 1, denom: stake}] = 1uatom, 1stake
- Show amounts as atoms: 100000uatom = 1atom
- Show short addresses: bech32 has a hashsum. The user then can doubletab to see the whole address
- Show sequence, account and chain-id late. Those information are barely critical.
- Hide gas? Fees are the important thing.

**Comment by faboweb** [comment]
Show address:
- Show the 0/0 address right away instead of forcing the user to click through
- Double clicking the user can select the path

**Comment by jleni** [comment]
Most of these improvements are part of v2.14/v2.15 (as part of the simple/expert mode)
