### ISSUE TITLE
Support for MsgSetWithdrawAddress

### ISSUE THREAD

**Issue by vietnamese-chowder** [cosmos/ledger-cosmos#71]
I'm trying to sign a `MsgSetWithdrawAddress`, and correct me if I'm wrong, but it seems it's not supported currently. During signing I see `cosmos-sdk/MsgSetWithdrawAddress` as the message type as opposed to "Withdraw Address" or something like that and the withdraw address field name is also not "prettified" as with `MsgSend` or `MsgDelegate`, and sending with it throws a signature error. Can you please support this message type?

This is the message I'm passing to sign:

```
{
  "account_number": "8",
  "chain_id": "testing",
  "fee": {
    "amount": [
      {
        "amount": "5000",
        "denom": "uatom"
      }
    ],
    "gas": "200000"
  },
  "memo": "",
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSetWithdrawAddress",
      "value": {
        "delegator_address": "cosmos1hr9x0sjvel6z3vt9qny8sdd5gnnlgk0p69d6cv",
        "withdraw_address": "cosmos12d64j98tjjpqkx70r08aspc4nvntqp2w6wr2de"
      }
    },
    {
      "type": "cosmos-sdk/MsgWithdrawDelegationReward",
      "value": {
        "delegator_address": "cosmos1hr9x0sjvel6z3vt9qny8sdd5gnnlgk0p69d6cv",
        "validator_address": "cosmosvaloper13dr26wdygna3s8fdl5tlc45m2le2ydyddxzj49"
      }
    }
  ],
  "sequence": "7"
}
```

**Comment by vietnamese-chowder** [comment]
Not sure if necessary, but here is the documentation on this type of message: https://docs.cosmos.network/v0.44/core/proto-docs.html#cosmos.distribution.v1beta1.MsgSetWithdrawAddress

**Comment by ftheirs** [comment]
Messages were prettified and tests were added to the app to check these improvements! It will be available since next release! PR: https://github.com/cosmos/ledger-cosmos/pull/77
Thanks for reporting this issue!

PS: the transaction can be signed with previous versions of the app 😄
