### ISSUE TITLE
Add display substitutions for IBC transactions

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ledger-cosmos#73]
Given that SIGN_MODE_TEXTUAL is taking longer than expected. I propose adding the necessary substitutions for IBC transfers and other relevant transactions and denominations

Ref: [tx_display.c](https://github.com/cosmos/ledger-cosmos/blob/main/app/src/tx_display.c#L455)

**Comment by ftheirs** [comment]
Hi @fedekunze! The specs for SIGN_MODE_TEXTUAL are ready and we've started with the development!

**Comment by ainhoa-a** [comment]
See here https://github.com/cosmos/ledger-cosmos/pull/75
