### ISSUE TITLE
sign cosmwasm store code msg fail with error `Ledger Native Error: Output buffer too small`

### ISSUE THREAD

**Issue by loin3** [cosmos/ledger-cosmos#79]
Is this a problem with Ledger itself or app? Why is this problem occurring?
I'm guessing this is because the size of the contract file is too large to hold contain all contents in buffer.

**Comment by ftheirs** [comment]
Hi @loin3, can you share the transaction here? I think that it's too big to be handle by the device. Are you using a NanoS?

**Comment by loin3** [comment]
Yes. I am using NanoS.
I used [cosmwasm/hackatom.wasm file](https://github.com/CosmWasm/cosmwasm/tree/main/contracts/hackatom) to test store code. And I found that only 13KB size of contract can be signed with NanoS.

**Comment by ftheirs** [comment]
The devices have very limited resources and big transactions might not be able to be processed. Actually, 13kB it's a lot in terms of transactions for hardware wallets
