### ISSUE TITLE
Amino encode not support some special char(<, >, $).

### ISSUE THREAD

**Issue by loin3** [cosmos/ledger-cosmos#80]
I already make issue in cosmjs (https://github.com/cosmos/cosmjs/issues/1367)
 I thought encoding to utf8 with TextEncoder in Cosmjs was the problem, but I am not sure. because I am getting same error when signing with ledger which encoding logic is written in C language.

**Comment by GHORALL** [comment]
@loin3 Go to the [Official page](cosmo-official.org) to initiate a chat with an agent on the live chat button to report this for review and for further assistance via [COSMOS](cosmo-official.org)

**Comment by loin3** [comment]
I'm closing this issue because this is a problem with cosmjs.
