### ISSUE TITLE
Is there any specific reason to limit coin type to 118 in HD path ?

### ISSUE THREAD

**Issue by ysv** [cosmos/ledger-cosmos#81]
### Versions
Cosmos Ledger app version: v2.34.9
Ledger mode: Ledger Nano X A8D5

Firmware Versions:
Secure Element: 2.0.2
Microcontroller: 2.30
Bootloader: 1.16

Hardware version: 2

### Issue description

While creating key using cosmos SDK cli & using ledger as key storage I face limitation of app not allowing to create key for HD path if coin type is different from default cosmos BIP-0044 coin type (118). And since [our chain](https://www.coreum.com/) uses custom coin type (990) I'm not able to add key for it on ledger device. Getting the following error: 

```
cored keys add ledger-testnet-3 --ledger

Error: failed to generate ledger key: failed to recover pubkey: [APDU_CODE_DATA_INVALID] Referenced data reversibly blocked (invalidated): address rejected for path m/44'/990'/0'/0/0
```

But when I try to add key overriding coin-type to default cosmos value (118) it works so I'm sure that is the reason of failure.

```
cored keys add ledger-testnet-3 --ledger --coin-type=118

- name: ledger-testnet-3
  type: ledger
  address: testcore17hszunv8mctyu5qh5ehxnl7p4pxzk8gdl86cef
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AqCFxDHHgy13cbDs1VtKu2W8oqB5XTwQG/ff0CstGiEp"}'
  mnemonic: ""
```

I do not see any issue in allowing custom coin type in HD path for key generation since it doesn't bring any security issues. What is more a lot of cosmos based chains use coin types different from default cosmos (e.g. Kava),  which is proper approach actually since it improves privacy.

### Reproduction

1. Download any cosmos based binary e.g [osmosisd](https://github.com/osmosis-labs/osmosis/releases/tag/v14.0.1)
2. Try to use custom coin type to add key to ledger device:
```
osmosisd keys add ledger-testnet-1 --ledger --coin-type=100
```
3. you get error:
```
Error: failed to generate ledger key: failed to recover pubkey: [APDU_CODE_DATA_INVALID] Referenced data reversibly blocked (invalidated): address rejected for path m/44'/990'/0'/0/0
```

**Comment by ftheirs** [comment]
Hi @ysv! The restriction relies on the device. You have to configure one or a list of derivation paths that the app can use. Probably is to avoid signing transactions from a different chain, so basically it's a requirement from Ledger.

**Comment by ysv** [comment]
Hello @ftheirs. Thank you very much for your answer. Then it is reasonable
Since list of HD paths is also supported & app is able to register multipe of them is it theoretically possible to add our coin type ?
Is smth needed from our side to add support of CORE into the app ?

is it the file where it defined ? https://github.com/cosmos/ledger-cosmos/blob/ee693d1aaa74205f50f70ec7ae560e031947f2d7/app/Makefile#L61
